### ISSUE TITLE
Jacobian callback function issue in Ipopt interface

### ISSUE THREAD

**Issue by VishnuDevA7** [ImperialCollegeLondon/ICLOCS#10]
I have been encountering these errors some times during the mesh-refinement step, more often when ICLOCS is used to solve with Warm Start option in Multi-Phase problems. The errors originate in Ipopt interface only during the MR step before the 1st iteration begins : 

***********************************************************************************************************88
Number of nonzeros in equality constraint Jacobian...:   157693
Number of nonzeros in inequality constraint Jacobian.:  3409545
Number of nonzeros in Lagrangian Hessian.............:        0

Matlab exception:
std::exception
*** Error using Ipopt Matlab interface: ***
There was an error when executing the Jacobian callback function.

Exception of type: IpoptException in file "Unknown File" at line -1:
 Exception message: Unknown Exception caught in Ipopt
Index exceeds matrix dimensions.
Error in solveSingleNLP_DirectCollocation_MultiPhase (line 297)
    sol.multipliers.lambda(data.phasedata{i}.zidx.org.const,1)=solution.mp.multipliers.lambda(data.phasedata{i}.zidx.mp.const,1);
Error in solveNLP (line 55)
            [solution,status,data]=solveSingleNLP_DirectCollocation_MultiPhase(NLP,data);
Error in solveMyProblem (line 78)
                [solution,status,data] = solveNLP(infoNLP,data);      % Solve the NLP
Error in main_eLeg_ThreePhase (line 6)
[solution,MRHistory]=solveMyProblem( problem,guess,options);      

Any clues ?

**Comment by VishnuDevA7** [comment]
On second thoughts, I suspect this issue could also arise when the problem gets too large, especially the Jacobian matrices. But I do not have direct control over mesh sizes to verify this effect.

**Comment by yuanbonie** [comment]
Hi Vishnu,

This error indicate that there a error is encountered when executing the file containing the internal dynamics. When this only happens occationally, it generally means that for certain combinations of the solution variables inside or slightly outside the variable simple bounds, this custom file can not be successfully evaluated. 

One example just to demonstrate this: if you define a look up table (e.g. interpolation) to obtain r form the value of x, with x defined to be between [-1 1] both for the lookup table and as simple bounds in ICLOCS.  If for some reason a value that is slightly outside the bound is requrested, e.g. when x=-1.001, the table look-up will fail and lead to an error. Potential reasons for this to happen can be due to finite difference perturbations at the variable boundaries, or after a mesh refinement where the denser mesh is initialized with the solution trajectory of the old mesh, which might have constraint violations in between the old coarse collocation points. 

Therefore, the key to solve this issue is to ensure the code inside the internal dynamics function can be successfully evaluated for all combinations of the solution variables inside or slightly outside their variable simple bounds

**Comment by VishnuDevA7** [comment]
Ok, by solution variables, you mean the solution from the previous iteration just before the mesh-refinement right ? Or could it be some finite difference perturbation vector for the solution variables  that are generated in the mesh-refinement step ?

**Comment by yuanbonie** [comment]
These are two independent possibliities to demonstrate cases where the event will happen:

- During mesh refinement, additional nodes are added and intialized with old solution. When the old solution is at its bound, e.g. two mesh node both have value at -1, depending on the interpolation scheme, there is still the chance that the interpolating polynoimal have a value of -1.001 in the middle of the mesh interval and a point added there will be initialized as -1.001. Although the optimization run after the refinement will take care of this, it still needs your custom function to be able to successfully evaluate this infeasible solution with a node at -1.001. Otherwise an error will occur right after refinement. 

- In side a NLP solve, if you choose to supply the derivatives with numerical finite difference, when the solution is a the boundary, say -1, to get numerial derivatives, it might need to perturb in both directions, evaluating the function at -1+delta and -1-delta. If the custom function can not be successfully evaluated at this slight out of bound point -1-delta, the solver will also throw an error. 

There are many other situations where the error seem to happen only occationally. Prevention of this situation is to ensure the internal dynamics function can be successfully evaluated for all combinations of the solution variables inside or slightly outside their variable simple bounds

**Comment by VishnuDevA7** [comment]
Ok, I figured for some combination of solution variables, one of the matrix that my dynamics function was trying to invert was singular and was returning Inf values.
