### ISSUE TITLE
Confused documentation in tutorials

### ISSUE THREAD

**Issue by maximiliano1985** [ImperialCollegeLondon/ICLOCS#15]
What is the correct definition of the hessians for Mayer term?
Some examples state:
`HE -  hessian of E wrt **[tf p x0 u0 uf xf]** or a subset of its variables`
but others:
`HE -  hessian of E wrt **[x0 xf u0 uf p tf]** or a subset of its variables`

**Comment by yuanbonie** [comment]
Sorry for the confusion. In ICLOCS2 earlier versions, the configuration is different depending on the discretization methods and whether the problem is free end-time or not. In version 2.5 onwards, the ordering has been unified to [x0 xf u0 uf p t0 tf]. I have updated the notes in the example problems to make them the same as the descriptions in new templates.

**Comment by maximiliano1985** [comment]
Fantastic, I had to deep dive into the library to reconstruct the order of the operations and I imagined that the code from Paola Falugi was referring an older interface.
Great job with ICLOCS2 by the way: I'm periodically following your improvements and like them a lot!
