### ISSUE TITLE
postSolveAnalysis Issue

### ISSUE THREAD

**Issue by VishnuDevA7** [ImperialCollegeLondon/ICLOCS#8]
Hi, I am solving a multi-phase optimization problem with the following settings :
options.stateRep = 'cubic';
options.inoutRep = 'quadratic';
options.resultRep = 'manual';
options.discretization = 'Hermite';

Now after IPOPT has found an optimal solution, postSolveAnalysis.m file throws an error at line 261.  I further noticed that there are no cases defined for 'cubic' or 'quadratic' option for the particular switch case routine.

**Comment by yuanbonie** [comment]
Hi Vishnu,

I did not recreate this error however i realize line 261 is for p/hp method. Therefore, I guess you have called the problem with 2 arguments like
phaseoptions{1}=problem.phases{1}.settings(20,5)
instead of 1, like 
phaseoptions{1}=problem.phases{1}.settings(20). 

The idea is that once you give 2 arguments, it will overide the discretization choice and default to LGR method with the second argument being the order of the polynomial.

**Comment by VishnuDevA7** [comment]
Yes, you were right. But what I don't understand is can't I use options.resultRep = 'manual' and 'quadratic' or 'cubic' for state or input result representation ? Because the settings file has allows me to do so.

**Comment by yuanbonie** [comment]
Hi Vishnu,

Yes the setting file allow you select that, but behind each option, the limitations are listed, for example:
('cubic'), available for Hermite-Simpson transcription method  

If you used LGR method, then you can only manually select the corresponding representation method that support LGR

Hope this helps to explain.

**Comment by VishnuDevA7** [comment]
Thanks, that clarifies !
